python_tests(
    runtime_package_dependencies=[
        "era_5g_relay_network_application:client",
        "era_5g_relay_network_application:server",
    ],
    dependencies=[":conftest"],
)

resources(name="conftest", sources=["conftest.py"])
