name: Pants

on: [pull_request]

jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == '5G-ERA' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Noop
        run: "true"
  build:
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    name: Perform CI Checks
    needs: org-check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - run: | 
        sudo apt-get update
        sudo apt-get install -y ros-humble-rosbridge-library ros-humble-cv-bridge ros-humble-sensor-msgs-py
    - uses: pantsbuild/actions/init-pants@v5-scie-pants
      with:
        gha-cache-key: cache0-py${{ matrix.python-version }}
        named-caches-hash: ${{ hashFiles('python-default.lock') }}
    - name: Check BUILD files
      run:  |
        pants tailor --check update-build-files --check ::
    - name: Lint and typecheck
      run: | 
        pants lint check ::
    - name: Test
      run: |
        source /opt/ros/humble/setup.bash
        pants test ::
    - name: Build and install packages
      run: |
        # We also smoke test that our release process will work by running `package`.
        pants package ::
        # this helps to check for cyclic dependencies or other problems
        python -m venv ./tstvenv
        source ./tstvenv/bin/activate
        pip install dist/*.tar.gz
        pip install pipdeptree
        pipdeptree -w fail
    - name: Upload pants log
      uses: actions/upload-artifact@v3
      with:
        name: pants-log
        path: .pants.d/pants.log
      if: always()  # We want the log even on failures.